import { STU1, STU2, STU3, STU4, STU5 } from "../asserts/Students";

export const Students = [
  {
    id: 1,
    name: "John Doe",
    registered_id: "319129510043",
    branch: "Computer Science Engineering",
    achievements: ["First place in coding competition", "Best project award"],
    image: STU1,
    email_id: "john.doe@example.com",
    cgpa: 9.8,
    total_classes: 300,
    presented: 250,
    absents: 50,
  },
  {
    id: 2,
    name: "Jane Smith",
    registered_id: "319129510044",
    branch: "Mechanical Engineering",
    achievements: ["Outstanding performance in robotics competition"],
    image: STU2,
    email_id: "jane.smith@example.com",
    cgpa: 9.5,
    total_classes: 300,
    presented: 270,
    absents: 30,
  },
  {
    id: 3,
    name: "Alice Johnson",
    registered_id: "319129510045",
    branch: "Electrical Electronics Engineering",
    achievements: ["Published research paper in renowned journal"],
    image: STU3,
    email_id: "alice.johnson@example.com",
    cgpa: 9.9,
    total_classes: 300,
    presented: 280,
    absents: 20,
  },
  {
    id: 4,
    name: "Bob Williams",
    registered_id: "319129510046",
    branch: "Civil Engineering",
    achievements: ["Won architecture design competition"],
    image: STU4,
    email_id: "bob.williams@example.com",
    cgpa: 8.7,
    total_classes: 300,
    presented: 260,
    absents: 40,
  },
  {
    id: 5,
    name: "Eva Brown",
    registered_id: "319129510047",
    branch: "Information Technology",
    achievements: ["Top performer in cybersecurity hackathon"],
    image: STU5,
    email_id: "eva.brown@example.com",
    cgpa: 5.0,
    total_classes: 300,
    presented: 290,
    absents: 10,
  },
  {
    id: 6,
    name: "Michael Lee",
    registered_id: "319129510048",
    branch: "Computer Science Engineering",
    achievements: ["Best academic performance award"],
    image: STU2,
    email_id: "michael.lee@example.com",
    cgpa: 7.6,
    total_classes: 300,
    presented: 270,
    absents: 30,
  },
  {
    id: 7,
    name: "Sophia Martinez",
    registered_id: "319129510049",
    branch: "Mechanical Engineering",
    achievements: ["Received scholarship for research project"],
    image: STU4,
    email_id: "sophia.martinez@example.com",
    cgpa: 8.8,
    total_classes: 300,
    presented: 280,
    absents: 20,
  },
  {
    id: 8,
    name: "William Taylor",
    registered_id: "319129510050",
    branch: "Electrical Electronics Engineering",
    achievements: ["Presented paper at international conference"],
    image: STU1,
    email_id: "william.taylor@example.com",
    cgpa: 3.9,
    total_classes: 300,
    presented: 290,
    absents: 10,
  },
  {
    id: 9,
    name: "Olivia Johnson",
    registered_id: "YZA567",
    branch: "Civil Engineering",
    achievements: ["Won environmental sustainability award"],
    image: STU2,
    email_id: "olivia.johnson@example.com",
    cgpa: 6.7,
    total_classes: 300,
    presented: 260,
    absents: 40,
  },
  {
    id: 10,
    name: "James Brown",
    registered_id: "BCD890",
    branch: "Information Technology",
    achievements: ["Developed innovative mobile application"],
    image: STU5,
    email_id: "james.brown@example.com",
    cgpa: 8.5,
    total_classes: 300,
    presented: 270,
    absents: 30,
  },
  {
    id: 11,
    name: "Emma Wilson",
    registered_id: "EFG123",
    branch: "Computer Science Engineering",
    achievements: ["Received outstanding coder award"],
    image: "emma_wilson.jpg",
    email_id: "emma.wilson@example.com",
    cgpa: 3.9,
    total_classes: 300,
    presented: 280,
    absents: 20,
  },
  {
    id: 12,
    name: "Daniel Garcia",
    registered_id: "HIJ456",
    branch: "Mechanical Engineering",
    achievements: ["Secured internship at top automotive company"],
    image: "daniel_garcia.jpg",
    email_id: "daniel.garcia@example.com",
    cgpa: 3.6,
    total_classes: 300,
    presented: 270,
    absents: 30,
  },
  {
    id: 13,
    name: "Ava Rodriguez",
    registered_id: "KLM789",
    branch: "Electrical Electronics Engineering",
    achievements: ["Published research paper in IEEE journal"],
    image: "ava_rodriguez.jpg",
    email_id: "ava.rodriguez@example.com",
    cgpa: 3.8,
    total_classes: 300,
    presented: 250,
    absents: 50,
  },
];
